name: caml-mimic
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.8.11
  - tqdm
  - scikit-learn
  - pandas
  - jupyter
  - gensim
  - nltk
  - pytorch
  - conda-build
  - pytorch
  - pandas
  - rich
  - pydantic
  - wandb