name: GitHub Actions Demo
on: [push]
jobs:
  Test-CAML-model :
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: "Checkout the code (&lfs)"
        uses: actions/checkout@v3
        with:
            lfs: 'true'
      - name: "Checkout LFS objects"
        run: git lfs checkout
      - name: "Display all files in the workspace"
        run: |
          ls ${{ github.workspace }}
      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('etc/example-environment.yml') }}
      - name: "Setup Conda Dependencies"
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: caml-mimic
          environment-file: environment.yml
          python-version: 3.8.11
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - run: conda list
      - run: conda info
      - name: "Set PYTHONPATH"
        run: |
          conda develop .
          echo ${PYTHONPATH}
          which python
#      - name: "Test the model on test data"
#        working-directory: ${{ github.workspace }}/predictions/CAML_mimic3_full/
#        run: bash evaluate_model.sh
      - name: "Setup bentoml"
        run: pip install "bentoml[all]"
      - name: "Convert model to bentoml"
        working-directory: ${{github.workspace}}/production/
        run: |
          python convert_to_bentoml.py --vocab-dicts-file ../mimic3_vocab_dicts.json --filter-size 10 --num-filter-maps 50 --model-path ${{ github.workspace }}/predictions/CAML_mimic3_full//model.pth
      - name: "Build bentoml"
        working-directory: ${{github.workspace}}/production/
        run: bentoml build --version latest -f bentofile.yaml .
      - name: "Containerize Bentoml model"
        working-directory: ${{ github.workspace}}/production/
        run: bentoml containerize caml_model_pretrained:latest
